name: NASM Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up NASM
      uses: ilammy/setup-nasm@v2
      with:
        nasm-version: '2.16.01'

    - name: Build NASM Code
      run: |
        nasm bootloader/bootloader.asm -f bin -o dist/bootloader.bin
        cp dist/bootloader.bin dist/zync_os.img
        truncate -s 1440k dist/zync_os.img