name: OS Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.0'

      - name: Install nasm
        run: sudo apt-get install -y nasm

      - name: Install mtools
        run: sudo apt-get install -y mtools

      - name: Install DOS-FS tools
        run: sudo apt-get install -y dosfstools

      - name: Build OS image
        run: npm run build

      - name: Clean up build
        run: npm run clean