name: OS Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Golang
        run: sudo apt-get install -y golang

      - name: Install NASM
        run: sudo apt-get install -y nasm

      - name: Install mtools
        run: sudo apt-get install -y mtools

      - name: Install DOS-FS tools
        run: sudo apt-get install -y dosfstools

      - name: Install Qrepo
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/nthnn/Qrepo/master/support/install.sh)"

      - name: Build OS image
        run: qrepo run build

      - name: Clean up build
        run: qrepo run clean
