name: OS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Golang
        run: brew install golang@1.21

      - name: Install NASM
        run: brew install nasm

      - name: Install mtools
        run: brew install mtools

      - name: Install DOS-FS tools
        run: brew install dosfstools

      - name: Install Qrepo
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/nthnn/Qrepo/master/support/install.sh)"

      - name: Build OS image
        run: qrepo run build

      - name: Clean up build
        run: qrepo run clean
